##
# Bug with Travis rubocop and rainbow gem
# resolve:
# https://github.com/rubocop-hq/rubocop/issues/6398#issuecomment-431898694
inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - Rakefile
  UseCache: true
  NewCops: enable

Metrics/LineLength:
  Max: 120
  IgnoredPatterns: ['\s*\#\s.*$']
  Exclude:
    - 'spec/**/*'
    - 'lib/cyclone_lariat/abstract/client.rb'
    - 'lib/cyclone_lariat/migration.rb'

Style/Documentation:
  Exclude:
    - '**/*'

Metrics/ParameterLists:
  Exclude:
    - '**/*'

Metrics/MethodLength:
  Exclude:
    - '**/*'

Style/AccessorGrouping:
  Exclude:
    - 'lib/cyclone_lariat/event.rb'
    - 'lib/cyclone_lariat/messages/abstract.rb'

Layout/EmptyLinesAroundAttributeAccessor:
  Exclude:
    - 'lib/cyclone_lariat/messages/abstract.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/cyclone_lariat/event.rb'
    - 'lib/cyclone_lariat/messages/abstract.rb'
    - 'lib/cyclone_lariat/migration.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/cyclone_lariat/event.rb'
    - 'lib/cyclone_lariat/messages/abstract.rb'
    - 'lib/cyclone_lariat/migration.rb'

Metrics/AbcSize:
  Exclude:
    - '**/*'

Metrics/BlockLength:
  Exclude:
    - '**/*'
    -
Layout/FirstHashElementIndentation:
  Exclude:
    - '**/*'

Metrics/ClassLength:
  Exclude:
    - 'lib/cyclone_lariat/migration.rb'
    - 'lib/cyclone_lariat/abstract/client.rb'
    - 'lib/cyclone_lariat/sns.rb'

Lint/RescueException:
  Exclude:
    - 'lib/cyclone_lariat/middleware.rb'
